15: Ensure transactions saved as they finish rather than in DESTROY
PopeFelix/Mojo-UserAgent-Mockable pull request #16
Opened 2017-06-14 08:43 UTC by ungrim97

2017-06-14 08:45 UTC, ungrim97 commented
PR to fix issue #15

2017-06-14 14:29 UTC, PopeFelix commented on Changes
> +- #15: Fixed issue where save wouldn't work if called during global destruction
Mark that as "Issue 15", otherwise folk are going to be wondering what the "15" means. :)

2017-06-14 18:46 UTC, PopeFelix requested changes

2017-06-14 18:46 UTC, PopeFelix commented on Changes
> +- #15: Fixed issue where save wouldn't work if called during global destruction
I like this, and it all looks pretty good. However, I'd like to see a unit test that shows all transactions having been recorded without the thing going out of scope.

2018-11-22 04:56 UTC, PopeFelix approved these changes
Oh, to hell with it. Let's just merge it and hope for the best.

2018-11-22 05:13 UTC, merged

2018-11-22 05:36 UTC, PopeFelix commented
In v 1.56